#######################################################################################
# Book settings
title: Jason Liu
author: Jason Liu
copyright: "2020"
logo: "logo.png"

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/jasoneliu/pessoalab
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
