#######################################################################################
# Book settings
title: Jason Liu
author: Jason Liu
copyright: "2020"
logo: "logo.png"

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: ""

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/jasoneliu/pessoalab2020
latex:
  latex_engine: "xelatex"
  
#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js